
package com.stylemigration.stylemigration.service.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Application", targetNamespace = "transFormService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Application {


    /**
     * 
     * @param base64Code
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "trans")
    @WebResult(name = "transResult", targetNamespace = "transFormService")
    @RequestWrapper(localName = "trans", targetNamespace = "transFormService", className = "com.stylemigration.stylemigration.service.webservice.Trans")
    @ResponseWrapper(localName = "transResponse", targetNamespace = "transFormService", className = "com.stylemigration.stylemigration.service.webservice.TransResponse")
    public String trans(
        @WebParam(name = "base64Code", targetNamespace = "transFormService")
        String base64Code);

}
